### ISSUE TITLE
Bread hasn't added the (properly working) 32-bit binary I compiled

### ISSUE THREAD

**Issue by dexteruseslinux** [breadtard/uwuTools#1]
I compiled the 32-bit binary again in a Debian 32-bit VM. I'm dexteruseslinux#8570, btw - make sure to say that I compiled the 32-bit version!

**Comment by SlowDexter26** [comment]
also, this is my old github username

**Comment by SlowDexter26** [comment]
Oh, and the 32-bit binary is here. Tested, working.
https://drive.google.com/file/d/1Wdw9TfGjiQuKwPb5zK-ZvKu2NMeAuBa0/view?usp=sharing

**Comment by breadtard** [comment]
Added working binary. Thanks

**Issue closed**
